FIND_PATH(FLANN_INCLUDE_DIR flann PATHS /usr/include /usr/local/include/ opt/local/include)
FIND_LIBRARY(FLANN NAMES flann PATHS /usr/lib /usr/local/lib /opt/local/lib)
FIND_LIBRARY(LZ4 NAMES lz4 PATHS /usr/lib /usr/local/lib /opt/local/lib)

IF (FLANN_INCLUDE_DIR AND FLANN)
   SET(FLANN_LIBRARIES ${FLANN})
   SET(FLANN_FOUND TRUE)
ELSE ()
   SET(FLANN_LIBRARIES "NOTFOUND")
   SET(FLANN_FOUND FALSE)
ENDIF ()

IF (NOT FLANN_FOUND)
   IF (FLANN_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find FLANN")
   ENDIF ()
ENDIF ()

MARK_AS_ADVANCED(FLANN_INCLUDE_DIR FLANN_LIBRARIES)