FIND_PATH(NanoFLANN_PATH nanoflann.hpp PATHS /usr /opt /var)

IF (NanoFLANN_PATH)
   SET(NanoFLANN_INCLUDE_DIR ${NanoFLANN_PATH})
   SET(NanoFLANN_FOUND TRUE)
ELSE ()
   SET(NanoFLANN_INCLUDE_DIR "NOTFOUND")
   SET(NanoFLANN_FOUND FALSE)
ENDIF ()

IF (NOT NanoFLANN_FOUND AMD NanoFLANN_FIND_REQUIRED)
   MESSAGE(FATAL_ERROR "Could not find NanoFLANN")
ENDIF ()

MARK_AS_ADVANCED(NanoFLANN_INCLUDE_DIR)