MESSAGE(STATUS "CMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}")
MESSAGE(STATUS "CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION}")

IF(CMAKE_SYSTEM_NAME MATCHES Linux)
    FIND_PATH(NETCDF_INCLUDE_DIR netcdf.h PATHS /usr/include /usr/local/include /opt/local/include) 
    FIND_LIBRARY(NETCDF NAMES netcdf PATHS /usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64)
    FIND_LIBRARY(NETCDF_CPP NAMES netcdf_c++ PATHS /usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64)
ELSEIF(CMAKE_SYSTEM_NAME MATCHES Darwin)
	FIND_PATH(NETCDF_INCLUDE_DIR netcdf PATHS /usr/include /usr/local/include /opt/local/include)
	FIND_LIBRARY(NETCDF NAMES netcdf PATHS /usr/lib /usr/local/lib /opt/local/lib)
	FIND_LIBRARY(NETCDF_CPP NAMES netcdf-cxx4 netcdf_c++ PATHS /usr/lib /usr/local/lib /opt/local/lib)
ENDIF()	    

IF (NOT NETCDF_INCLUDE_DIR)
	MESSAGE(WARNING "Could not locate NETCDF_INCLUDE_DIR")
ENDIF()

IF (NOT NETCDF)
	MESSAGE(WARNING "Could not locate libnetcdf")
ENDIF()

IF (NOT NETCDF_CPP)
	MESSAGE(WARNING "Could not locate libnetcdf_c++")
ENDIF()

IF (NETCDF_INCLUDE_DIR AND NETCDF AND NETCDF_CPP)
	SET(NETCDF_FOUND TRUE)
	# SET(NETCDF_LIBRARIES "-L /usr/local/lib -lnetcdf_c++ -lnetcdf")
	SET(NETCDF_LIBRARIES ${NETCDF} ${NETCDF_CPP})
ELSE()
   SET(NETCDF_LIBRARIES "NOTFOUND")
ENDIF()

IF (NOT NETCDF_FOUND AND NETCDF_FIND_REQUIRED)
   MESSAGE(FATAL_ERROR "Could not find NETCDF")
ENDIF ()
