FROM debian:stable

ARG VISIT_VERSION="3.1.2"
ARG VISIT_PKG_URL="https://portal.nersc.gov/project/visit/releases/3.1.2/visit3_1_2.linux-x86_64-debian9.tar.gz"
ARG VISIT_INSTALLER=visit-install3_1_2
ARG VISIT_INSTALLER_URL="https://portal.nersc.gov/project/visit/releases/3.1.2/${VISIT_INSTALLER}"

RUN apt-get -y update --fix-missing
RUN apt-get -y upgrade 
RUN apt-get -y dist-upgrade
RUN apt-get -y install software-properties-common
RUN apt-get -y update 
RUN apt-get -y install \
wget git cmake cpio \
gcc g++ libomp5 \
python python-pip \
libboost-all-dev libflann1.9 libflann-dev blitz++ \
shapelib libhdf5-dev netcdf-bin libnetcdf-dev libnetcdf-c++4 libnetcdf-c++4-dev zlib1g zlib1g-dev \
vtk7 libvtk7-dev
RUN pip install setuptools external utils

# # Visualisation
# RUN pip install Cython h5py "netCDF4>=1.3.0<1.4.0"
# RUN apt-get -y --fix-missing  install gnuplot vtk7 libvtk7-dev
# RUN wget --quiet ${VISIT_INSTALLER_URL} && wget --quiet ${VISIT_PKG_URL} && chmod u+x ./${VISIT_INSTALLER}
# RUN rm -rf /usr/local/visit &&\
#   mkdir -p /usr/local/visit/3.1.2+/linux-x86_64/bin &&\
#   echo "1" | ./visit-install3_1_2 3.1.2 linux-x86_64-debian9 /usr/local/visit
# ENV VISIT_EXECUTABLE=/usr/local/visit/bin/visit

# libradolan
RUN git clone https://github.com/JuergenSimon/radolan.git
RUN cd radolan && cmake . && make install && cd ..

# Meanie3D
RUN git clone https://github.com/JuergenSimon/meanie3D
WORKDIR /meanie3D
RUN git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*" && git fetch --all
RUN git checkout --track remotes/origin/dockerize
RUN git pull && cmake -DPRESET=docker-vtk . && make install

# Cleanup
WORKDIR /
RUN rm -rf meanie3D radolan 
RUN apt-get remove -y wget git cmake cpio 
RUN apt autoremove -y

# Prepare for runtime
RUN mkdir /data
ENV LD_LIBRARY_PATH=/usr/local/lib
ENTRYPOINT ["/usr/local/bin/meanie3D"]