#ifndef _M3D_DEFINES_H_
#define _M3D_DEFINES_H_

// Threading

#define WITH_TBB 1
#define WITH_BOOST_THREADS 0

#define PROVIDE_THREADSAFETY 0

#if WITH_BOOST_THREADS
	#define PROVIDE_MUTEX 1
#endif

#if WITH_TBB
	#define PROVIDE_MUTEX 1
#endif

// Featurespace debugging

#define DEBUG_MEANSHIFT_GRAPH 0
#define DEBUG_CLUSTER_MERGING 0
#define DEBUG_CLUSTER_MERGING_DECISION 1
#define DEBUG_TRACKING 1
#define DEBUG_HISTOGRAM_CORRELATION 0

#define WRITE_MEANSHIFT_VECTORS 0
#define WRITE_CLUSTERS 0
#define WRITE_BOUNDARIES 0

#endif
